// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6n2f9aOcD0aLbFydFb-ssi2Zkhg0WsLI',
    appId: '1:785388423803:web:e26ca6232279e3997970de',
    messagingSenderId: '785388423803',
    projectId: 'mystore-d31aa',
    authDomain: 'mystore-d31aa.firebaseapp.com',
    storageBucket: 'mystore-d31aa.appspot.com',
    measurementId: 'G-L9NDSLR3RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-7RPZ9bK95nzn7l-YAUUwTR6zwGCcUPE',
    appId: '1:785388423803:android:83817182d3626a067970de',
    messagingSenderId: '785388423803',
    projectId: 'mystore-d31aa',
    storageBucket: 'mystore-d31aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbhOAS2yrpUZyRC8rryk8R2zNmiZUQLps',
    appId: '1:785388423803:ios:79408bc72959358a7970de',
    messagingSenderId: '785388423803',
    projectId: 'mystore-d31aa',
    storageBucket: 'mystore-d31aa.appspot.com',
    iosClientId: '785388423803-2pgk48q8hm4up9ivd4ljn24mjvmet62q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myStoreDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbhOAS2yrpUZyRC8rryk8R2zNmiZUQLps',
    appId: '1:785388423803:ios:79408bc72959358a7970de',
    messagingSenderId: '785388423803',
    projectId: 'mystore-d31aa',
    storageBucket: 'mystore-d31aa.appspot.com',
    iosClientId: '785388423803-2pgk48q8hm4up9ivd4ljn24mjvmet62q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myStoreDev',
  );
}
